using AngularJS_Test2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace AngularJS_Test2.Controllers
{
    public class CountryController : ApiController
    {
        //List<Tuple<string, string, string>> countriesWithRegions = new List<Tuple<string, string, string>>();
        List<Tuple<string,  string>> countries = new List<Tuple<string,  string>>();
        List<Continent> continents = new List<Continent>();
       
        [HttpGet]
        public object Search(string term = "")
        {
            PopulateCountries();
            PopulateContinents();
            if (!string.IsNullOrEmpty(term))
            {
                var matchingContinent = continents.Where( x=> ( x.Name.ToLower().Contains(term.ToLower()) || x.Countries.Any(y=>y.Name.ToLower().Contains(term.ToLower())) ) );
                foreach (var cont in matchingContinent)
                {
                    cont.Countries = cont.Countries.Where(y => y.Name.ToLower().Contains(term.ToLower())).ToList();
                }
               
                //return countries.Where(x => x.Item1.ToLower().Contains(term.ToLower()) || x.Item2.ToLower().Contains(term.ToLower()));
                return GetJsonViewModel(matchingContinent);
                
            }
            return GetJsonViewModel(continents);
        }

        private List<object> GetJsonViewModel(IEnumerable<Continent> continents)
        {
            List<object> list = new List<object>();

            foreach (var continent in continents)
            {
                list.Add(new { name = continent.Name, Continent = continent.Name, Country = "" });
                foreach (var country in continent.Countries)
                {
                    list.Add(new { name = country.Name, Continent = continent.Name, Country = country.Name });
                }
            }

            return list;
        }

        private void PopulateContinents()
        {
            var africa = new Continent { Name = "Africa" };
            var america = new Continent { Name = "America" };
            var asia = new Continent { Name = "Asia" };
            var europe = new Continent { Name = "Europe" };
            var oceania = new Continent { Name = "Oceania" };

            continents.Add(africa);
            continents.Add(america);
            continents.Add(asia);
            continents.Add(europe);
            continents.Add(oceania);

            africa.Countries.Add(new Country { Name = "Burundi", Continent = africa });
            africa.Countries.Add(new Country { Name = "Comoros", Continent = africa });
            africa.Countries.Add(new Country { Name = "Djibouti", Continent = africa });
            africa.Countries.Add(new Country { Name = "Eritrea", Continent = africa });
            africa.Countries.Add(new Country { Name = "Ethiopia", Continent = africa });
            africa.Countries.Add(new Country { Name = "Kenya", Continent = africa });
            africa.Countries.Add(new Country { Name = "Madagascar", Continent = africa });
            africa.Countries.Add(new Country { Name = "Malawi", Continent = africa });
            africa.Countries.Add(new Country { Name = "Mauritius", Continent = africa });
            africa.Countries.Add(new Country { Name = "Mayotte (France)", Continent = africa });
            africa.Countries.Add(new Country { Name = "Mozambique", Continent = africa });
            africa.Countries.Add(new Country { Name = "Rwanda", Continent = africa });
            africa.Countries.Add(new Country { Name = "Seychelles", Continent = africa });
            africa.Countries.Add(new Country { Name = "Somalia", Continent = africa });
            africa.Countries.Add(new Country { Name = "Uganda", Continent = africa });
            africa.Countries.Add(new Country { Name = "United Republic of Tanzania", Continent = africa });
            africa.Countries.Add(new Country { Name = "Zambia", Continent = africa });
            africa.Countries.Add(new Country { Name = "Zimbabwe", Continent = africa });
            africa.Countries.Add(new Country { Name = "Angola", Continent = africa });
            africa.Countries.Add(new Country { Name = "Cameroon", Continent = africa });
            africa.Countries.Add(new Country { Name = "Central African Republic", Continent = africa });
            africa.Countries.Add(new Country { Name = "Chad", Continent = africa });
            africa.Countries.Add(new Country { Name = "Congo", Continent = africa });
            africa.Countries.Add(new Country { Name = "Democratic Republic of the Congo", Continent = africa });
            africa.Countries.Add(new Country { Name = "Equatorial Guinea", Continent = africa });
            africa.Countries.Add(new Country { Name = "Gabon", Continent = africa });
            africa.Countries.Add(new Country { Name = "Sao Tome and Principe", Continent = africa });
            africa.Countries.Add(new Country { Name = "Algeria", Continent = africa });
            africa.Countries.Add(new Country { Name = "Egypt", Continent = africa });
            africa.Countries.Add(new Country { Name = "Libya", Continent = africa });
            africa.Countries.Add(new Country { Name = "Morocco", Continent = africa });
            africa.Countries.Add(new Country { Name = "South Sudan", Continent = africa });
            africa.Countries.Add(new Country { Name = "Sudan", Continent = africa });
            africa.Countries.Add(new Country { Name = "Tunisia", Continent = africa });
            africa.Countries.Add(new Country { Name = "Western Sahara", Continent = africa });
            africa.Countries.Add(new Country { Name = "Botswana", Continent = africa });
            africa.Countries.Add(new Country { Name = "Lesotho", Continent = africa });
            africa.Countries.Add(new Country { Name = "Namibia", Continent = africa });
            africa.Countries.Add(new Country { Name = "South Africa", Continent = africa });
            africa.Countries.Add(new Country { Name = "Swaziland", Continent = africa });
            africa.Countries.Add(new Country { Name = "Benin", Continent = africa });
            africa.Countries.Add(new Country { Name = "Burkina Faso", Continent = africa });
            africa.Countries.Add(new Country { Name = "Cape Verde", Continent = africa });
            africa.Countries.Add(new Country { Name = "Gambia", Continent = africa });
            africa.Countries.Add(new Country { Name = "Ghana", Continent = africa });
            africa.Countries.Add(new Country { Name = "Guinea", Continent = africa });
            africa.Countries.Add(new Country { Name = "Guinea-Bissau", Continent = africa });
            africa.Countries.Add(new Country { Name = "Liberia", Continent = africa });
            africa.Countries.Add(new Country { Name = "Mali", Continent = africa });
            africa.Countries.Add(new Country { Name = "Mauritania", Continent = africa });
            africa.Countries.Add(new Country { Name = "Niger", Continent = africa });
            africa.Countries.Add(new Country { Name = "Nigeria", Continent = africa });
            africa.Countries.Add(new Country { Name = "Saint Helena", Continent = africa });
            africa.Countries.Add(new Country { Name = "Senegal", Continent = africa });
            africa.Countries.Add(new Country { Name = "Sierra Leone", Continent = africa });
            africa.Countries.Add(new Country { Name = "Togo", Continent = africa });
            america.Countries.Add(new Country { Name = "Anguilla", Continent = america });
            america.Countries.Add(new Country { Name = "Antigua and Barbuda", Continent = america });
            america.Countries.Add(new Country { Name = "Aruba (The Netherlands)", Continent = america });
            america.Countries.Add(new Country { Name = "Bahamas", Continent = america });
            america.Countries.Add(new Country { Name = "Barbados", Continent = america });
            america.Countries.Add(new Country { Name = "British Virgin Islands", Continent = america });
            america.Countries.Add(new Country { Name = "Cayman Islands", Continent = america });
            america.Countries.Add(new Country { Name = "Cuba", Continent = america });
            america.Countries.Add(new Country { Name = "Dominica", Continent = america });
            america.Countries.Add(new Country { Name = "Dominican Republic", Continent = america });
            america.Countries.Add(new Country { Name = "Grenada", Continent = america });
            america.Countries.Add(new Country { Name = "Guadeloupe (France)", Continent = america });
            america.Countries.Add(new Country { Name = "Haiti", Continent = america });
            america.Countries.Add(new Country { Name = "Jamaica", Continent = america });
            america.Countries.Add(new Country { Name = "Martinique (France)", Continent = america });
            america.Countries.Add(new Country { Name = "Montserrat", Continent = america });
            america.Countries.Add(new Country { Name = "Puerto Rico (The United States of America)", Continent = america });
            america.Countries.Add(new Country { Name = "Saint Kitts and Nevis", Continent = america });
            america.Countries.Add(new Country { Name = "Saint Lucia", Continent = america });
            america.Countries.Add(new Country { Name = "Saint Vincent and the Grenadines", Continent = america });
            america.Countries.Add(new Country { Name = "Trinidad and Tobago", Continent = america });
            america.Countries.Add(new Country { Name = "Turks and Caicos Islands", Continent = america });
            america.Countries.Add(new Country { Name = "United States Virgin Islands", Continent = america });
            america.Countries.Add(new Country { Name = "Belize", Continent = america });
            america.Countries.Add(new Country { Name = "Costa Rica", Continent = america });
            america.Countries.Add(new Country { Name = "El Salvador", Continent = america });
            america.Countries.Add(new Country { Name = "Guatemala", Continent = america });
            america.Countries.Add(new Country { Name = "Honduras", Continent = america });
            america.Countries.Add(new Country { Name = "Mexico", Continent = america });
            america.Countries.Add(new Country { Name = "Nicaragua", Continent = america });
            america.Countries.Add(new Country { Name = "Panama", Continent = america });
            america.Countries.Add(new Country { Name = "Bermuda", Continent = america });
            america.Countries.Add(new Country { Name = "Canada", Continent = america });
            america.Countries.Add(new Country { Name = "Greenland (Denmark)", Continent = america });
            america.Countries.Add(new Country { Name = "Saint Pierre and Miquelon (France)", Continent = america });
            america.Countries.Add(new Country { Name = "United States of America", Continent = america });
            america.Countries.Add(new Country { Name = "Argentina", Continent = america });
            america.Countries.Add(new Country { Name = "Bolivia (Plurinational State of)", Continent = america });
            america.Countries.Add(new Country { Name = "Brazil", Continent = america });
            america.Countries.Add(new Country { Name = "Chile", Continent = america });
            america.Countries.Add(new Country { Name = "Colombia", Continent = america });
            america.Countries.Add(new Country { Name = "Ecuador", Continent = america });
            america.Countries.Add(new Country { Name = "Falkland Islands (Malvinas)", Continent = america });
            america.Countries.Add(new Country { Name = "Guyana", Continent = america });
            america.Countries.Add(new Country { Name = "Paraguay", Continent = america });
            america.Countries.Add(new Country { Name = "Peru", Continent = america });
            america.Countries.Add(new Country { Name = "Suriname", Continent = america });
            america.Countries.Add(new Country { Name = "Uruguay", Continent = america });
            america.Countries.Add(new Country { Name = "Venezuela (Bolivarian Republic of)", Continent = america });
            asia.Countries.Add(new Country { Name = "Kazakhstan", Continent = asia });
            asia.Countries.Add(new Country { Name = "Kyrgyzstan", Continent = asia });
            asia.Countries.Add(new Country { Name = "Tajikistan", Continent = asia });
            asia.Countries.Add(new Country { Name = "Turkmenistan", Continent = asia });
            asia.Countries.Add(new Country { Name = "Uzbekistan", Continent = asia });
            asia.Countries.Add(new Country { Name = "China", Continent = asia });
            asia.Countries.Add(new Country { Name = "China - Hong Kong (Special Administrative Region)", Continent = asia });
            asia.Countries.Add(new Country { Name = "China - Macau (Special Administrative Region)", Continent = asia });
            asia.Countries.Add(new Country { Name = "China - Taiwan Province", Continent = asia });
            asia.Countries.Add(new Country { Name = "Democratic People's Republic of Korea", Continent = asia });
            asia.Countries.Add(new Country { Name = "Democratic People's Republic of Korea", Continent = asia });
            asia.Countries.Add(new Country { Name = "Japan", Continent = asia });
            asia.Countries.Add(new Country { Name = "Mongolia", Continent = asia });
            asia.Countries.Add(new Country { Name = "Brunei Darussalam", Continent = asia });
            asia.Countries.Add(new Country { Name = "Cambodia", Continent = asia });
            asia.Countries.Add(new Country { Name = "Indonesia", Continent = asia });
            asia.Countries.Add(new Country { Name = "Lao People's Democratic Republic", Continent = asia });
            asia.Countries.Add(new Country { Name = "Malaysia", Continent = asia });
            asia.Countries.Add(new Country { Name = "Myanmar", Continent = asia });
            asia.Countries.Add(new Country { Name = "Philippines", Continent = asia });
            asia.Countries.Add(new Country { Name = "Singapore", Continent = asia });
            asia.Countries.Add(new Country { Name = "Thailand", Continent = asia });
            asia.Countries.Add(new Country { Name = "Timor-Leste", Continent = asia });
            asia.Countries.Add(new Country { Name = "Viet Nam", Continent = asia });
            asia.Countries.Add(new Country { Name = "Afghanistan", Continent = asia });
            asia.Countries.Add(new Country { Name = "Bangladesh", Continent = asia });
            asia.Countries.Add(new Country { Name = "Bhutan", Continent = asia });
            asia.Countries.Add(new Country { Name = "India", Continent = asia });
            asia.Countries.Add(new Country { Name = "Iran (Islamic Republic of)", Continent = asia });
            asia.Countries.Add(new Country { Name = "Maldives", Continent = asia });
            asia.Countries.Add(new Country { Name = "Nepal", Continent = asia });
            asia.Countries.Add(new Country { Name = "Pakistan", Continent = asia });
            asia.Countries.Add(new Country { Name = "Sri Lanka", Continent = asia });
            asia.Countries.Add(new Country { Name = "Armenia", Continent = asia });
            asia.Countries.Add(new Country { Name = "Azerbaijan", Continent = asia });
            asia.Countries.Add(new Country { Name = "Bahrain", Continent = asia });
            asia.Countries.Add(new Country { Name = "Cyprus", Continent = asia });
            asia.Countries.Add(new Country { Name = "Georgia", Continent = asia });
            asia.Countries.Add(new Country { Name = "Iraq", Continent = asia });
            asia.Countries.Add(new Country { Name = "Israel", Continent = asia });
            asia.Countries.Add(new Country { Name = "Jordan", Continent = asia });
            asia.Countries.Add(new Country { Name = "Kuwait", Continent = asia });
            asia.Countries.Add(new Country { Name = "Lebanon", Continent = asia });
            asia.Countries.Add(new Country { Name = "Occupied Palestinian Territory", Continent = asia });
            asia.Countries.Add(new Country { Name = "Oman", Continent = asia });
            asia.Countries.Add(new Country { Name = "Qatar", Continent = asia });
            asia.Countries.Add(new Country { Name = "Saudi Arabia", Continent = asia });
            asia.Countries.Add(new Country { Name = "Syria", Continent = asia });
            asia.Countries.Add(new Country { Name = "Turkey", Continent = asia });
            asia.Countries.Add(new Country { Name = "United Arab Emirates", Continent = asia });
            asia.Countries.Add(new Country { Name = "Yemen ", Continent = asia });
            europe.Countries.Add(new Country { Name = "Belarus", Continent = europe });
            europe.Countries.Add(new Country { Name = "Bulgaria", Continent = europe });
            europe.Countries.Add(new Country { Name = "Czech Republic", Continent = europe });
            europe.Countries.Add(new Country { Name = "Hungary", Continent = europe });
            europe.Countries.Add(new Country { Name = "Moldova", Continent = europe });
            europe.Countries.Add(new Country { Name = "Poland", Continent = europe });
            europe.Countries.Add(new Country { Name = "Romania", Continent = europe });
            europe.Countries.Add(new Country { Name = "Russian Fed. - Chechnya", Continent = europe });
            europe.Countries.Add(new Country { Name = "Russian Federation", Continent = europe });
            europe.Countries.Add(new Country { Name = "Slovakia", Continent = europe });
            europe.Countries.Add(new Country { Name = "Ukraine", Continent = europe });
            europe.Countries.Add(new Country { Name = "Aland Islands (Finland)", Continent = europe });
            europe.Countries.Add(new Country { Name = "Channel Islands", Continent = europe });
            europe.Countries.Add(new Country { Name = "Denmark", Continent = europe });
            europe.Countries.Add(new Country { Name = "Estonia", Continent = europe });
            europe.Countries.Add(new Country { Name = "Finland", Continent = europe });
            europe.Countries.Add(new Country { Name = "Iceland", Continent = europe });
            europe.Countries.Add(new Country { Name = "Ireland", Continent = europe });
            europe.Countries.Add(new Country { Name = "Isle of Man (The United Kingdom of Great Britain and Northern Ireland)", Continent = europe });
            europe.Countries.Add(new Country { Name = "Latvia", Continent = europe });
            europe.Countries.Add(new Country { Name = "Lithuania", Continent = europe });
            europe.Countries.Add(new Country { Name = "Norway", Continent = europe });
            europe.Countries.Add(new Country { Name = "Svalbard and Jan Mayen Islands", Continent = europe });
            europe.Countries.Add(new Country { Name = "Sweden", Continent = europe });
            europe.Countries.Add(new Country { Name = "United Kingdom of Great Britain and Northern Ireland ", Continent = europe });
            europe.Countries.Add(new Country { Name = "Albania", Continent = europe });
            europe.Countries.Add(new Country { Name = "Andorra", Continent = europe });
            europe.Countries.Add(new Country { Name = "Bosnia and Herzegovina", Continent = europe });
            europe.Countries.Add(new Country { Name = "Croatia", Continent = europe });
            europe.Countries.Add(new Country { Name = "Gibraltar", Continent = europe });
            europe.Countries.Add(new Country { Name = "Greece", Continent = europe });
            europe.Countries.Add(new Country { Name = "Holy See", Continent = europe });
            europe.Countries.Add(new Country { Name = "Italy", Continent = europe });
            europe.Countries.Add(new Country { Name = "Kosovo", Continent = europe });
            europe.Countries.Add(new Country { Name = "Malta", Continent = europe });
            europe.Countries.Add(new Country { Name = "Montenegro", Continent = europe });
            europe.Countries.Add(new Country { Name = "Portugal", Continent = europe });
            europe.Countries.Add(new Country { Name = "San Marino", Continent = europe });
            europe.Countries.Add(new Country { Name = "Serbia", Continent = europe });
            europe.Countries.Add(new Country { Name = "Slovenia", Continent = europe });
            europe.Countries.Add(new Country { Name = "Spain", Continent = europe });
            europe.Countries.Add(new Country { Name = "The former Yugoslav Republic of Macedonia", Continent = europe });
            europe.Countries.Add(new Country { Name = "Austria", Continent = europe });
            europe.Countries.Add(new Country { Name = "Belgium", Continent = europe });
            europe.Countries.Add(new Country { Name = "France", Continent = europe });
            europe.Countries.Add(new Country { Name = "Germany", Continent = europe });
            europe.Countries.Add(new Country { Name = "Liechtenstein", Continent = europe });
            europe.Countries.Add(new Country { Name = "Luxembourg", Continent = europe });
            europe.Countries.Add(new Country { Name = "Monaco", Continent = europe });
            europe.Countries.Add(new Country { Name = "Netherlands", Continent = europe });
            europe.Countries.Add(new Country { Name = "Netherlands Antilles (The Netherlands)", Continent = europe });
            europe.Countries.Add(new Country { Name = "Switzerland", Continent = europe });
            oceania.Countries.Add(new Country { Name = "Australia", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "New Zealand", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Norfolk Island (Australia)", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Fiji", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "New Caledonia (France)", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Papua New Guinea", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Solomon Islands", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Vanuatu", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Guam", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Kiribati", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Marshall Islands", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Micronesia (Federated States of)", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Nauru", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Northern Mariana Islands (The United States of America)", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Palau", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "American Samoa", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Cook Islands", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Niue (New Zealand)", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Pitcairn Island", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Samoa", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Tokelau", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Tonga", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Tuvalu", Continent = oceania });
            oceania.Countries.Add(new Country { Name = "Wallis and Futuna (France) ", Continent = oceania });



        }

        private void PopulateCountries()
        {
            countries.Add(new Tuple<string, string>("Africa", "Burundi"));
            countries.Add(new Tuple<string, string>("Africa", "Comoros"));
            countries.Add(new Tuple<string, string>("Africa", "Djibouti"));
            countries.Add(new Tuple<string, string>("Africa", "Eritrea"));
            countries.Add(new Tuple<string, string>("Africa", "Ethiopia"));
            countries.Add(new Tuple<string, string>("Africa", "Kenya"));
            countries.Add(new Tuple<string, string>("Africa", "Madagascar"));
            countries.Add(new Tuple<string, string>("Africa", "Malawi"));
            countries.Add(new Tuple<string, string>("Africa", "Mauritius"));
            countries.Add(new Tuple<string, string>("Africa", "Mayotte (France)"));
            countries.Add(new Tuple<string, string>("Africa", "Mozambique"));
            countries.Add(new Tuple<string, string>("Africa", "Rwanda"));
            countries.Add(new Tuple<string, string>("Africa", "Seychelles"));
            countries.Add(new Tuple<string, string>("Africa", "Somalia"));
            countries.Add(new Tuple<string, string>("Africa", "Uganda"));
            countries.Add(new Tuple<string, string>("Africa", "United Republic of Tanzania"));
            countries.Add(new Tuple<string, string>("Africa", "Zambia"));
            countries.Add(new Tuple<string, string>("Africa", "Zimbabwe"));
            countries.Add(new Tuple<string, string>("Africa", "Angola"));
            countries.Add(new Tuple<string, string>("Africa", "Cameroon"));
            countries.Add(new Tuple<string, string>("Africa", "Central African Republic"));
            countries.Add(new Tuple<string, string>("Africa", "Chad"));
            countries.Add(new Tuple<string, string>("Africa", "Congo"));
            countries.Add(new Tuple<string, string>("Africa", "Democratic Republic of the Congo"));
            countries.Add(new Tuple<string, string>("Africa", "Equatorial Guinea"));
            countries.Add(new Tuple<string, string>("Africa", "Gabon"));
            countries.Add(new Tuple<string, string>("Africa", "Sao Tome and Principe"));
            countries.Add(new Tuple<string, string>("Africa", "Algeria"));
            countries.Add(new Tuple<string, string>("Africa", "Egypt"));
            countries.Add(new Tuple<string, string>("Africa", "Libya"));
            countries.Add(new Tuple<string, string>("Africa", "Morocco"));
            countries.Add(new Tuple<string, string>("Africa", "South Sudan"));
            countries.Add(new Tuple<string, string>("Africa", "Sudan"));
            countries.Add(new Tuple<string, string>("Africa", "Tunisia"));
            countries.Add(new Tuple<string, string>("Africa", "Western Sahara"));
            countries.Add(new Tuple<string, string>("Africa", "Botswana"));
            countries.Add(new Tuple<string, string>("Africa", "Lesotho"));
            countries.Add(new Tuple<string, string>("Africa", "Namibia"));
            countries.Add(new Tuple<string, string>("Africa", "South Africa"));
            countries.Add(new Tuple<string, string>("Africa", "Swaziland"));
            countries.Add(new Tuple<string, string>("Africa", "Benin"));
            countries.Add(new Tuple<string, string>("Africa", "Burkina Faso"));
            countries.Add(new Tuple<string, string>("Africa", "Cape Verde"));
            countries.Add(new Tuple<string, string>("Africa", "Gambia"));
            countries.Add(new Tuple<string, string>("Africa", "Ghana"));
            countries.Add(new Tuple<string, string>("Africa", "Guinea"));
            countries.Add(new Tuple<string, string>("Africa", "Guinea-Bissau"));
            countries.Add(new Tuple<string, string>("Africa", "Liberia"));
            countries.Add(new Tuple<string, string>("Africa", "Mali"));
            countries.Add(new Tuple<string, string>("Africa", "Mauritania"));
            countries.Add(new Tuple<string, string>("Africa", "Niger"));
            countries.Add(new Tuple<string, string>("Africa", "Nigeria"));
            countries.Add(new Tuple<string, string>("Africa", "Saint Helena"));
            countries.Add(new Tuple<string, string>("Africa", "Senegal"));
            countries.Add(new Tuple<string, string>("Africa", "Sierra Leone"));
            countries.Add(new Tuple<string, string>("Africa", "Togo"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Anguilla"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Antigua and Barbuda"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Aruba (The Netherlands)"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Bahamas"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Barbados"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "British Virgin Islands"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Cayman Islands"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Cuba"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Dominica"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Dominican Republic"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Grenada"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Guadeloupe (France)"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Haiti"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Jamaica"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Martinique (France)"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Montserrat"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Puerto Rico (The United States of America)"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Saint Kitts and Nevis"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Saint Lucia"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Saint Vincent and the Grenadines"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Trinidad and Tobago"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Turks and Caicos Islands"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "United States Virgin Islands"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Belize"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Costa Rica"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "El Salvador"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Guatemala"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Honduras"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Mexico"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Nicaragua"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Panama"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Bermuda"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Canada"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Greenland (Denmark)"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Saint Pierre and Miquelon (France)"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "United States of America"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Argentina"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Bolivia (Plurinational State of)"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Brazil"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Chile"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Colombia"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Ecuador"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Falkland Islands (Malvinas)"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Guyana"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Paraguay"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Peru"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Suriname"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Uruguay"));
            countries.Add(new Tuple<string, string>("Americas & Caribbean", "Venezuela (Bolivarian Republic of)"));
            countries.Add(new Tuple<string, string>("Asia", "Kazakhstan"));
            countries.Add(new Tuple<string, string>("Asia", "Kyrgyzstan"));
            countries.Add(new Tuple<string, string>("Asia", "Tajikistan"));
            countries.Add(new Tuple<string, string>("Asia", "Turkmenistan"));
            countries.Add(new Tuple<string, string>("Asia", "Uzbekistan"));
            countries.Add(new Tuple<string, string>("Asia", "China"));
            countries.Add(new Tuple<string, string>("Asia", "China - Hong Kong (Special Administrative Region)"));
            countries.Add(new Tuple<string, string>("Asia", "China - Macau (Special Administrative Region)"));
            countries.Add(new Tuple<string, string>("Asia", "China - Taiwan Province"));
            countries.Add(new Tuple<string, string>("Asia", "Democratic People's Republic of Korea"));
            countries.Add(new Tuple<string, string>("Asia", "Democratic People's Republic of Korea"));
            countries.Add(new Tuple<string, string>("Asia", "Japan"));
            countries.Add(new Tuple<string, string>("Asia", "Mongolia"));
            countries.Add(new Tuple<string, string>("Asia", "Brunei Darussalam"));
            countries.Add(new Tuple<string, string>("Asia", "Cambodia"));
            countries.Add(new Tuple<string, string>("Asia", "Indonesia"));
            countries.Add(new Tuple<string, string>("Asia", "Lao People's Democratic Republic"));
            countries.Add(new Tuple<string, string>("Asia", "Malaysia"));
            countries.Add(new Tuple<string, string>("Asia", "Myanmar"));
            countries.Add(new Tuple<string, string>("Asia", "Philippines"));
            countries.Add(new Tuple<string, string>("Asia", "Singapore"));
            countries.Add(new Tuple<string, string>("Asia", "Thailand"));
            countries.Add(new Tuple<string, string>("Asia", "Timor-Leste"));
            countries.Add(new Tuple<string, string>("Asia", "Viet Nam"));
            countries.Add(new Tuple<string, string>("Asia", "Afghanistan"));
            countries.Add(new Tuple<string, string>("Asia", "Bangladesh"));
            countries.Add(new Tuple<string, string>("Asia", "Bhutan"));
            countries.Add(new Tuple<string, string>("Asia", "India"));
            countries.Add(new Tuple<string, string>("Asia", "Iran (Islamic Republic of)"));
            countries.Add(new Tuple<string, string>("Asia", "Maldives"));
            countries.Add(new Tuple<string, string>("Asia", "Nepal"));
            countries.Add(new Tuple<string, string>("Asia", "Pakistan"));
            countries.Add(new Tuple<string, string>("Asia", "Sri Lanka"));
            countries.Add(new Tuple<string, string>("Asia", "Armenia"));
            countries.Add(new Tuple<string, string>("Asia", "Azerbaijan"));
            countries.Add(new Tuple<string, string>("Asia", "Bahrain"));
            countries.Add(new Tuple<string, string>("Asia", "Cyprus"));
            countries.Add(new Tuple<string, string>("Asia", "Georgia"));
            countries.Add(new Tuple<string, string>("Asia", "Iraq"));
            countries.Add(new Tuple<string, string>("Asia", "Israel"));
            countries.Add(new Tuple<string, string>("Asia", "Jordan"));
            countries.Add(new Tuple<string, string>("Asia", "Kuwait"));
            countries.Add(new Tuple<string, string>("Asia", "Lebanon"));
            countries.Add(new Tuple<string, string>("Asia", "Occupied Palestinian Territory"));
            countries.Add(new Tuple<string, string>("Asia", "Oman"));
            countries.Add(new Tuple<string, string>("Asia", "Qatar"));
            countries.Add(new Tuple<string, string>("Asia", "Saudi Arabia"));
            countries.Add(new Tuple<string, string>("Asia", "Syria"));
            countries.Add(new Tuple<string, string>("Asia", "Turkey"));
            countries.Add(new Tuple<string, string>("Asia", "United Arab Emirates"));
            countries.Add(new Tuple<string, string>("Asia", "Yemen "));
            countries.Add(new Tuple<string, string>("Europe", "Belarus"));
            countries.Add(new Tuple<string, string>("Europe", "Bulgaria"));
            countries.Add(new Tuple<string, string>("Europe", "Czech Republic"));
            countries.Add(new Tuple<string, string>("Europe", "Hungary"));
            countries.Add(new Tuple<string, string>("Europe", "Moldova"));
            countries.Add(new Tuple<string, string>("Europe", "Poland"));
            countries.Add(new Tuple<string, string>("Europe", "Romania"));
            countries.Add(new Tuple<string, string>("Europe", "Russian Fed. - Chechnya"));
            countries.Add(new Tuple<string, string>("Europe", "Russian Federation"));
            countries.Add(new Tuple<string, string>("Europe", "Slovakia"));
            countries.Add(new Tuple<string, string>("Europe", "Ukraine"));
            countries.Add(new Tuple<string, string>("Europe", "Aland Islands (Finland)"));
            countries.Add(new Tuple<string, string>("Europe", "Channel Islands"));
            countries.Add(new Tuple<string, string>("Europe", "Denmark"));
            countries.Add(new Tuple<string, string>("Europe", "Estonia"));
            countries.Add(new Tuple<string, string>("Europe", "Finland"));
            countries.Add(new Tuple<string, string>("Europe", "Iceland"));
            countries.Add(new Tuple<string, string>("Europe", "Ireland"));
            countries.Add(new Tuple<string, string>("Europe", "Isle of Man (The United Kingdom of Great Britain and Northern Ireland)"));
            countries.Add(new Tuple<string, string>("Europe", "Latvia"));
            countries.Add(new Tuple<string, string>("Europe", "Lithuania"));
            countries.Add(new Tuple<string, string>("Europe", "Norway"));
            countries.Add(new Tuple<string, string>("Europe", "Svalbard and Jan Mayen Islands"));
            countries.Add(new Tuple<string, string>("Europe", "Sweden"));
            countries.Add(new Tuple<string, string>("Europe", "United Kingdom of Great Britain and Northern Ireland "));
            countries.Add(new Tuple<string, string>("Europe", "Albania"));
            countries.Add(new Tuple<string, string>("Europe", "Andorra"));
            countries.Add(new Tuple<string, string>("Europe", "Bosnia and Herzegovina"));
            countries.Add(new Tuple<string, string>("Europe", "Croatia"));
            countries.Add(new Tuple<string, string>("Europe", "Gibraltar"));
            countries.Add(new Tuple<string, string>("Europe", "Greece"));
            countries.Add(new Tuple<string, string>("Europe", "Holy See"));
            countries.Add(new Tuple<string, string>("Europe", "Italy"));
            countries.Add(new Tuple<string, string>("Europe", "Kosovo"));
            countries.Add(new Tuple<string, string>("Europe", "Malta"));
            countries.Add(new Tuple<string, string>("Europe", "Montenegro"));
            countries.Add(new Tuple<string, string>("Europe", "Portugal"));
            countries.Add(new Tuple<string, string>("Europe", "San Marino"));
            countries.Add(new Tuple<string, string>("Europe", "Serbia"));
            countries.Add(new Tuple<string, string>("Europe", "Slovenia"));
            countries.Add(new Tuple<string, string>("Europe", "Spain"));
            countries.Add(new Tuple<string, string>("Europe", "The former Yugoslav Republic of Macedonia"));
            countries.Add(new Tuple<string, string>("Europe", "Austria"));
            countries.Add(new Tuple<string, string>("Europe", "Belgium"));
            countries.Add(new Tuple<string, string>("Europe", "France"));
            countries.Add(new Tuple<string, string>("Europe", "Germany"));
            countries.Add(new Tuple<string, string>("Europe", "Liechtenstein"));
            countries.Add(new Tuple<string, string>("Europe", "Luxembourg"));
            countries.Add(new Tuple<string, string>("Europe", "Monaco"));
            countries.Add(new Tuple<string, string>("Europe", "Netherlands"));
            countries.Add(new Tuple<string, string>("Europe", "Netherlands Antilles (The Netherlands)"));
            countries.Add(new Tuple<string, string>("Europe", "Switzerland"));
            countries.Add(new Tuple<string, string>("Oceania", "Australia"));
            countries.Add(new Tuple<string, string>("Oceania", "New Zealand"));
            countries.Add(new Tuple<string, string>("Oceania", "Norfolk Island (Australia)"));
            countries.Add(new Tuple<string, string>("Oceania", "Fiji"));
            countries.Add(new Tuple<string, string>("Oceania", "New Caledonia (France)"));
            countries.Add(new Tuple<string, string>("Oceania", "Papua New Guinea"));
            countries.Add(new Tuple<string, string>("Oceania", "Solomon Islands"));
            countries.Add(new Tuple<string, string>("Oceania", "Vanuatu"));
            countries.Add(new Tuple<string, string>("Oceania", "Guam"));
            countries.Add(new Tuple<string, string>("Oceania", "Kiribati"));
            countries.Add(new Tuple<string, string>("Oceania", "Marshall Islands"));
            countries.Add(new Tuple<string, string>("Oceania", "Micronesia (Federated States of)"));
            countries.Add(new Tuple<string, string>("Oceania", "Nauru"));
            countries.Add(new Tuple<string, string>("Oceania", "Northern Mariana Islands (The United States of America)"));
            countries.Add(new Tuple<string, string>("Oceania", "Palau"));
            countries.Add(new Tuple<string, string>("Oceania", "American Samoa"));
            countries.Add(new Tuple<string, string>("Oceania", "Cook Islands"));
            countries.Add(new Tuple<string, string>("Oceania", "Niue (New Zealand)"));
            countries.Add(new Tuple<string, string>("Oceania", "Pitcairn Island"));
            countries.Add(new Tuple<string, string>("Oceania", "Samoa"));
            countries.Add(new Tuple<string, string>("Oceania", "Tokelau"));
            countries.Add(new Tuple<string, string>("Oceania", "Tonga"));
            countries.Add(new Tuple<string, string>("Oceania", "Tuvalu"));
            countries.Add(new Tuple<string, string>("Oceania", "Wallis and Futuna (France) "));

        }

        //private void PopulateCountriesWithRegions()
        //{
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "Burundi"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "Comoros"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "Djibouti"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "Eritrea"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "Ethiopia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "Kenya"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "Madagascar"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "Malawi"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "Mauritius"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "Mayotte (France)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "Mozambique"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "Rwanda"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "Seychelles"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "Somalia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "Uganda"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "United Republic of Tanzania"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "Zambia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Eastern Africa", "Zimbabwe"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Middle Africa", "Angola"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Middle Africa", "Cameroon"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Middle Africa", "Central African Republic"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Middle Africa", "Chad"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Middle Africa", "Congo"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Middle Africa", "Democratic Republic of the Congo"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Middle Africa", "Equatorial Guinea"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Middle Africa", "Gabon"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Middle Africa", "Sao Tome and Principe"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Northern Africa", "Algeria"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Northern Africa", "Egypt"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Northern Africa", "Libya"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Northern Africa", "Morocco"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Northern Africa", "South Sudan"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Northern Africa", "Sudan"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Northern Africa", "Tunisia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Northern Africa", "Western Sahara"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Southern Africa", "Botswana"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Southern Africa", "Lesotho"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Southern Africa", "Namibia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Southern Africa", "South Africa"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Southern Africa", "Swaziland"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Western Africa", "Benin"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Western Africa", "Burkina Faso"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Western Africa", "Cape Verde"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Western Africa", "Gambia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Western Africa", "Ghana"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Western Africa", "Guinea"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Western Africa", "Guinea-Bissau"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Western Africa", "Liberia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Western Africa", "Mali"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Western Africa", "Mauritania"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Western Africa", "Niger"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Western Africa", "Nigeria"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Western Africa", "Saint Helena"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Western Africa", "Senegal"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Western Africa", "Sierra Leone"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Africa", "Western Africa", "Togo"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Anguilla"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Antigua and Barbuda"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Aruba (The Netherlands)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Bahamas"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Barbados"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "British Virgin Islands"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Cayman Islands"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Cuba"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Dominica"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Dominican Republic"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Grenada"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Guadeloupe (France)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Haiti"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Jamaica"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Martinique (France)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Montserrat"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Puerto Rico (The United States of America)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Saint Kitts and Nevis"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Saint Lucia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Saint Vincent and the Grenadines"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Trinidad and Tobago"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "Turks and Caicos Islands"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Caribbean", "United States Virgin Islands"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Central America", "Belize"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Central America", "Costa Rica"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Central America", "El Salvador"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Central America", "Guatemala"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Central America", "Honduras"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Central America", "Mexico"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Central America", "Nicaragua"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Central America", "Panama"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Northern America", "Bermuda"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Northern America", "Canada"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Northern America", "Greenland (Denmark)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Northern America", "Saint Pierre and Miquelon (France)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "Northern America", "United States of America"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "South America", "Argentina"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "South America", "Bolivia (Plurinational State of)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "South America", "Brazil"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "South America", "Chile"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "South America", "Colombia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "South America", "Ecuador"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "South America", "Falkland Islands (Malvinas)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "South America", "Guyana"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "South America", "Paraguay"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "South America", "Peru"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "South America", "Suriname"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "South America", "Uruguay"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Americas & Caribbean", "South America", "Venezuela (Bolivarian Republic of)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Central Asia", "Kazakhstan"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Central Asia", "Kyrgyzstan"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Central Asia", "Tajikistan"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Central Asia", "Turkmenistan"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Central Asia", "Uzbekistan"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Eastern Asia", "China"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Eastern Asia", "China - Hong Kong (Special Administrative Region)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Eastern Asia", "China - Macau (Special Administrative Region)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Eastern Asia", "China - Taiwan Province"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Eastern Asia", "Democratic People's Republic of Korea"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Eastern Asia", "Democratic People's Republic of Korea"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Eastern Asia", "Japan"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Eastern Asia", "Mongolia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "South-Eastern Asia", "Brunei Darussalam"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "South-Eastern Asia", "Cambodia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "South-Eastern Asia", "Indonesia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "South-Eastern Asia", "Lao People's Democratic Republic"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "South-Eastern Asia", "Malaysia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "South-Eastern Asia", "Myanmar"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "South-Eastern Asia", "Philippines"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "South-Eastern Asia", "Singapore"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "South-Eastern Asia", "Thailand"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "South-Eastern Asia", "Timor-Leste"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "South-Eastern Asia", "Viet Nam"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Southern Asia", "Afghanistan"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Southern Asia", "Bangladesh"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Southern Asia", "Bhutan"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Southern Asia", "India"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Southern Asia", "Iran (Islamic Republic of)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Southern Asia", "Maldives"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Southern Asia", "Nepal"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Southern Asia", "Pakistan"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Southern Asia", "Sri Lanka"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "Armenia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "Azerbaijan"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "Bahrain"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "Cyprus"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "Georgia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "Iraq"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "Israel"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "Jordan"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "Kuwait"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "Lebanon"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "Occupied Palestinian Territory"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "Oman"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "Qatar"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "Saudi Arabia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "Syria"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "Turkey"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "United Arab Emirates"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Asia", "Western Asia", "Yemen "));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Eastern Europe", "Belarus"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Eastern Europe", "Bulgaria"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Eastern Europe", "Czech Republic"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Eastern Europe", "Hungary"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Eastern Europe", "Moldova"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Eastern Europe", "Poland"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Eastern Europe", "Romania"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Eastern Europe", "Russian Fed. - Chechnya"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Eastern Europe", "Russian Federation"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Eastern Europe", "Slovakia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Eastern Europe", "Ukraine"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Northern Europe", "Aland Islands (Finland)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Northern Europe", "Channel Islands"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Northern Europe", "Denmark"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Northern Europe", "Estonia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Northern Europe", "Finland"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Northern Europe", "Iceland"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Northern Europe", "Ireland"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Northern Europe", "Isle of Man (The United Kingdom of Great Britain and Northern Ireland)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Northern Europe", "Latvia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Northern Europe", "Lithuania"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Northern Europe", "Norway"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Northern Europe", "Svalbard and Jan Mayen Islands"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Northern Europe", "Sweden"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Northern Europe", "United Kingdom of Great Britain and Northern Ireland "));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Southern Europe", "Albania"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Southern Europe", "Andorra"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Southern Europe", "Bosnia and Herzegovina"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Southern Europe", "Croatia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Southern Europe", "Gibraltar"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Southern Europe", "Greece"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Southern Europe", "Holy See"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Southern Europe", "Italy"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Southern Europe", "Kosovo"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Southern Europe", "Malta"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Southern Europe", "Montenegro"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Southern Europe", "Portugal"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Southern Europe", "San Marino"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Southern Europe", "Serbia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Southern Europe", "Slovenia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Southern Europe", "Spain"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Southern Europe", "The former Yugoslav Republic of Macedonia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Western Europe", "Austria"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Western Europe", "Belgium"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Western Europe", "France"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Western Europe", "Germany"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Western Europe", "Liechtenstein"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Western Europe", "Luxembourg"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Western Europe", "Monaco"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Western Europe", "Netherlands"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Western Europe", "Netherlands Antilles (The Netherlands)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Europe", "Western Europe", "Switzerland"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Australia and New Zealand", "Australia"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Australia and New Zealand", "New Zealand"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Australia and New Zealand", "Norfolk Island (Australia)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Melanesia", "Fiji"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Melanesia", "New Caledonia (France)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Melanesia", "Papua New Guinea"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Melanesia", "Solomon Islands"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Melanesia", "Vanuatu"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Micronesia", "Guam"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Micronesia", "Kiribati"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Micronesia", "Marshall Islands"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Micronesia", "Micronesia (Federated States of)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Micronesia", "Nauru"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Micronesia", "Northern Mariana Islands (The United States of America)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Micronesia", "Palau"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Polynesia", "American Samoa"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Polynesia", "Cook Islands"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Polynesia", "Niue (New Zealand)"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Polynesia", "Pitcairn Island"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Polynesia", "Samoa"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Polynesia", "Tokelau"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Polynesia", "Tonga"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Polynesia", "Tuvalu"));
        //    countriesWithRegions.Add(new Tuple<string, string, string>("Oceania", "Polynesia", "Wallis and Futuna (France) "));



        //}


    }
}
